name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      working-directory: ./back
      run: pip install -r requirements.txt
    - name: Lint with pylint
      working-directory: ./back
      run: pylint *.py
    - name: Test with pytest
      working-directory: ./back
      run: python -m pytest
      env:
        ENV: test
